language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=artellapipe
- sphinx-apidoc -f -e -o docs/sphinx artellapipe
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: F1q6rWB57fTbcI3tv6BhKYUg2EIgc1UpLM1QJTT5/PjhpNsGWtVeynmGIP2jLM2s5FLPTPkiagxxoHTQF/nYJfwcBwroIMwuI7f465IvHeT0EQKwcMAwUAVXeKEVqVJ923VtFBljCRhv0cy/rbrylc9YmLW+/fWkiDAgag+HRi4jR8sQp1aiH+nyugQKpxaI94RLfsktQd9QW2tF/pXCUN49dlPEtUabuIv+TXcNB0TUBrAjpPsjCDdfSKJcl6rqg6wU39ZAbelqZUaw2f9zL7kCf3s74CwhbaLJQ4G4vl7RpjifEHmrlBqyFx8lWo/m/0FyUXTNIQyN8vmK2EbDmA74fYW9jxdvOE3Ti0ldPfic2S2U5ZG4caCN+OkCDc9Hs05zheniFKrG7Cr7uDd3Az75YPe/UpzUDnmw91eQWJQIXWIpwoViVAnXRNZzIiEq48ZyeZJxkbckw+q1Amw1D3tKUkw3KT77pSddBaymFq94iWb07L9IrEN5VGJ6/g9EjrElPKboPEc79uujr6tI/Kz+twJlpt88IUiArOrJKP9EVKWR/B4rl6xfjVrqceXugLzVpQDoUAKBwI7vM/taP+yZCxgh8CTNxniOdzq/NIGEHNYTdsywJXzzbl92/iSd8HOF/iNLBfP4geCC5U46e/bOvnIQnwfb+2rj7Zu6j5U=
    on:
      branch: master
      tags: true